site_name: PECAN
docs_dir: docs
repo_url: 'https://github.com/paulgarrettphd/PECAN.git'
repo_name: 'GitHub'
site_description:
  Host resources for early career acadmeics who study,
  research and teach psychological sciences at the
  University of Melbourne, Australia.
  

theme:
  name: null
  custom_dir: mkdocs-material\material
  static_templates:
    - 404.html
    
  include_search_page: false
  search_index_only: true
  
  language: en
  features:
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/PECAN.png
  icon:
    logo: logo
  
  plugins:
  - search
  - minify:
    minify_html: true
    
 # extra:
  # social:
    # - icon: fontawesome/brands/github
      # link: https://github.com/squidfunk
    # - icon: fontawesome/brands/gitter
      # link: https://gitter.im/squidfunk/mkdocs-material
    # - icon: fontawesome/brands/docker
      # link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    # - icon: fontawesome/brands/twitter
      # link: https://twitter.com/squidfunk
    # - icon: fontawesome/brands/linkedin
      # link: https://linkedin.com/in/squidfunk/
    # - icon: fontawesome/brands/instagram
      # link: https://instagram.com/squidfunk
  
  
    
nav:
  - PECAN: 
    - Welcome to PECAN: index.md
    - Aims: Aims.md
    - Committee: Committee.md
    - Events: Events.md
    - Members: Members.md
  - Resources: 
    - Networks & Committees: Resources_Networks.md
    - Grants: Resources_Grants.md
    - Workshops: Resources_Workshops.md
    - Academic Tools: Resources_ResearchTools.md
    - Awards: Resources_Awards.md
    - Outreach: Resources_Outreach.md
  - Contact: Contact.md
 
google_analytics: ['UA-193953779-2', 'auto']

#google_analytics:
#  - G-NETSS4SCMD
#  - auto
  